### ISSUE TITLE
Stylesheet issues

### ISSUE THREAD

**Issue by jiwantamang** [sprajwal078/angular-nepali-datepicker#1]
First of all thank you very much for this wonderful library. But I am having problems styling date picker with my custom css. Do you have any update on it.

**Comment by sprajwal078** [comment]
Sure. I have used css variables so that its easy for customization. I will either update the doc or reply to this issue. Meanwhile, could you please share with me the look you needed so I can think of how to accommodate easy customization? Thanks.

**Comment by sprajwal078** [comment]
Since I have not heard back from you I will close this issue. If you want to update styles you can add your styles to the component classes. You can inspect element and see for yourself the classes I have used. Please feel free to reopen this issue if you need any help. Thanks
