### ISSUE TITLE
Invalid number of months 

### ISSUE THREAD

**Issue by coderabin01** [sprajwal078/angular-nepali-datepicker#3]
**Bug 1
--------**
_**Steps to reproduce:**_

1. Select Baisakh 31st of 2076.
2. Select Chaitra of 2076.

**Actual Output:** Chaitra Month with 31 days.
**Expected Output:** Chaitra Month with 30 days.

**Bug 2:
-------**
_**Steps to reproduce:**_

1. Select Jestha 32nd of 2076.
2. Select Chaitra of 2076.

**Actual Output:** Chaitra Month with 32 days.
**Expected Output:** Chaitra Month with 30 days.

@sprajwal078 Can you please look through the issue? Thank you.

**Comment by sprajwal078** [comment]
hey @coderabin01. Thanks for pointing out the bug. I am working on.

**Comment by sprajwal078** [comment]
duplicate of #4
