### ISSUE TITLE
Invalid preview of days in month

### ISSUE THREAD

**Issue by coderabin01** [sprajwal078/angular-nepali-datepicker#4]
**_Steps to reproduce:_**

1. Current nepali date is set on the form input on page init.
2. When the date is set in the input form using drop down, the date in the input field changes but the calendar shows the previous month. 

_The screen shot is attached below._
![ng-np-dp](https://user-images.githubusercontent.com/24822399/69851901-f5744700-12aa-11ea-90f8-b20418c3e44f.PNG)

3. Only on second focus the calendar shows the selected month but still the days in the months are from previous selected month.

_The screen shot is attached below._
![ng-np-dp2](https://user-images.githubusercontent.com/24822399/69852013-4126f080-12ab-11ea-8216-5351c30d04fd.PNG)

Eg: On page reload, the date on the input field is 2076-8-1.
	On selecting Baisakh from the dropdown. The value in input field is set to 2076-1-1.
	On focus of the input field, the calendar shows the month of Poush.
	Again, on focus, the calendar shows the month of Jestha.

**Comment by sprajwal078** [comment]
Do you have a github or jsfiddle I can use? I'm trying to reproduce this on my end but not sure how to do this.

**Comment by sprajwal078** [comment]
@coderabin01 Thanks for pointing out the bug. I have released new version with the fix. Cheers.
